apiVersion: v1
kind: Service
metadata:
  labels:
    run: test-%NAME
  name: test-%NAME
  namespace: default
spec:
  type: NodePort
  selector:
    run: test-%NAME
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
