apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-%NAME
  labels:
    run: test-%NAME
  namespace: default
spec:
  replicas: %NUM
  selector:
    matchLabels:
      run: test-%NAME
  template:
    metadata:
      labels:
         run: test-%NAME
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: test
      dnsPolicy: ClusterFirst
      restartPolicy: Always
